= Cdmtools

Set of commands/tools to grab data (and eventually objects) from a CONTENTdm instance via https://www.oclc.org/support/services/contentdm/help/customizing-website-help/other-customizations/contentdm-api-reference.en.html[the server and web APIs].


== Installation

=== Dependencies

- You will need Ruby
- You will need a recent-ish version of bundler (`gem install bundler` will install if you don't have it, update it if you do)
- You will need https://github.com/mjordan/cdminspect[cdminspect] installed somewhere this application can find it

=== Steps
Clone this repo.

`cd` into the resulting directory

`bundle install`

Copy `config/config.yaml.example` to `config/config.yaml` and edit the new file with your details.

== Usage

For the available commands:

`exe/cdm help`

For details on exactly what each command does:

`exe/cdm help [COMMAND]`

*This command currently is the best documentation for each step.* Later, I will add some more info to https://github.com/lyrasis/cdmtools/wiki[the repo wiki].

=== Conceptual outline



=== Recommended initial order of commands for working with a new CDM instance

==== Data/metadata profiling

- get_coll_data
- get_dc_mappings
- get_field_data

At this point, you can see the number of collections you are working with and the way the metadata fields have been defined for them.

- get_top_records

Check your logfile for any errors or warnings at this point and resolve them before continuing, or your problems will just be compounded.

The tool creates a local JSON file for each successful API call, and tries to be pretty good at not making additional API calls to replace info you already have.

This means you can just re-run the above command to try to re-grab any records that could not be retrieved before. It will work fast and only grab what is missing. It also currently means that, if you want to refresh the records from the source, you will need to delete the local copies in `collalias/_cdmrecords`

Use `--force=true` to re-download records and compoundobject info you already retrieved.

- get_child_records

Use `--force=true` to re-download records you already retrieved.

Again, check your logfile after this step

- finalize_migration_records

*Now you can use https://github.com/lyrasis/mdmm[MDMM] to handle data reporting, cleanup, and remapping.*

==== Object data
- harvest_objects

Check logfile for errors/warnings after this step.

Simple objects: harvested file size is compared against cdmfilesize and warning is logged if the values do not match

Document-PDF objects: the single PDF is harvested. We don't have that filesize in the CDM record, so best practice will be to validate these objects outside this process

*Use `exe/cdm help` and `exe/cdm help [COMMAND]` to get more details on helper functions for harvesting and working with objects*

== Contributing

Bug reports and pull requests are welcome in https://github.com/lyrasis/cdmtools[the GitHub repo].

== License

The gem is available as open source under the terms of the https://opensource.org/licenses/MIT[MIT License].
